[tox]
envlist = py310, cov, cov_local
skip_missing_interpreters = True
ignore_basepython_conflict = True

[gh-actions]
python =
    3.10: py310

[testenv]
deps=
    pytest
    mock
commands=pytest

[testenv:cov]
basepython=python3.10
deps=
    pytest
    pytest-cov
    mock
commands=
    pytest --cov --cov-report= {posargs}

[testenv:cov_local]
basepython=python3.10
deps=
    pytest
    pytest-cov
    mock
commands=
    pytest --cov --cov-report=
    coverage report
    coverage html
